// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZj6k9L6dK70N6nju_tPqZCig6KddnKiQ',
    appId: '1:49787307204:web:c432ad16999c62e9a9b591',
    messagingSenderId: '49787307204',
    projectId: 'study-app-d9b8d',
    authDomain: 'study-app-d9b8d.firebaseapp.com',
    storageBucket: 'study-app-d9b8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4om5S_lkY-n58kb1tlMXZwqMSAtDbCg',
    appId: '1:49787307204:android:1e402725d94d6121a9b591',
    messagingSenderId: '49787307204',
    projectId: 'study-app-d9b8d',
    storageBucket: 'study-app-d9b8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDkNr9lSkuD5t-OSpCXCntQMWeqgVmHg',
    appId: '1:49787307204:ios:4a92da1f9240f493a9b591',
    messagingSenderId: '49787307204',
    projectId: 'study-app-d9b8d',
    storageBucket: 'study-app-d9b8d.appspot.com',
    iosClientId: '49787307204-87r944n7i35a8aj68sgobnm0khg4g2c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABDkNr9lSkuD5t-OSpCXCntQMWeqgVmHg',
    appId: '1:49787307204:ios:4a92da1f9240f493a9b591',
    messagingSenderId: '49787307204',
    projectId: 'study-app-d9b8d',
    storageBucket: 'study-app-d9b8d.appspot.com',
    iosClientId: '49787307204-87r944n7i35a8aj68sgobnm0khg4g2c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
